[pytest]
python_files=test_*.py
python_classes=*TestCase
python_functions=test_*
markers =
    unit: Select only unit tests
    integration: Select only integration tests
    asyncio: Select only asyncio tests
    gevent: Select only gevent tests
    tornado: Select only Tornado tests
    trio: Select only Trio tests
    twisted: Select only Twisted tests
    v2_5: RethinkDB 2.5+ compatible tests
