from collections.abc import Callable, Iterable, Mapping
from datetime import date, datetime
from typing import Any, Optional, Type, Union

from rethinkdb.ast import ImplicitVar, ReqlBinary, ReqlQuery, ReqlTzinfo
from rethinkdb.errors import (
    InvalidHandshakeStateError,
    QueryPrinter,
    ReqlAuthError,
    ReqlCompileError,
    ReqlCursorEmpty,
    ReqlDriverCompileError,
    ReqlDriverError,
    ReqlError,
    ReqlInternalError,
    ReqlNonExistenceError,
    ReqlOpFailedError,
    ReqlOpIndeterminateError,
    ReqlOperationError,
    ReqlPermissionError,
    ReqlQueryLogicError,
    ReqlResourceLimitError,
    ReqlRuntimeError,
    ReqlServerCompileError,
    ReqlTimeoutError,
    ReqlUserError,
)
from rethinkdb.net import Connection, Cursor, DefaultConnection
from rethinkdb.query import ReqlConstant

class RethinkDB:
    Connection: Type[Connection]
    Cursor: Type[Cursor]
    DEFAULT_PORT: int
    DefaultConnection: Type[DefaultConnection]
    def make_connection(
        connection_type: Any,
        kwargs: Any,
        host: Any = ...,
        port: Any = ...,
        db: Any = ...,
        user: Any = ...,
        password: Any = ...,
        timeout: Any = ...,
        ssl: Any = ...,
        url: Any = ...,
        handshake_version: Any = ...,
    ) -> Any: ...
    def add(arguments: Any) -> Any: ...
    def and_(arguments: Any) -> Any: ...
    april: ReqlConstant
    def args(arguments: Any) -> Any: ...
    def asc(arguments: Any) -> Any: ...
    august: ReqlConstant
    def avg(arguments: Any) -> Any: ...
    def binary(data: Any) -> Any: ...
    def bit_and(arguments: Any) -> Any: ...
    def bit_not(arguments: Any) -> Any: ...
    def bit_or(arguments: Any) -> Any: ...
    def bit_sal(arguments: Any) -> Any: ...
    def bit_sar(arguments: Any) -> Any: ...
    def bit_xor(arguments: Any) -> Any: ...
    def branch(arguments: Any) -> Any: ...
    def ceil(arguments: Any) -> Any: ...
    def circle(arguments: Any, kwargs: Any) -> Any: ...
    def contains(arguments: Any) -> Any: ...
    def count(arguments: Any) -> Any: ...
    def db(arguments: Any) -> Any: ...
    def db_create(arguments: Any) -> Any: ...
    def db_drop(arguments: Any) -> Any: ...
    def db_list(arguments: Any) -> Any: ...
    december: ReqlConstant
    def desc(arguments: Any) -> Any: ...
    def distance(arguments: Any, kwargs: Any) -> Any: ...
    def distinct(arguments: Any) -> Any: ...
    def div(arguments: Any) -> Any: ...
    def do(arguments: Any) -> Any: ...
    def epoch_time(arguments: Any) -> Any: ...
    def eq(arguments: Any) -> Any: ...
    def error(msg: Any) -> Any: ...
    february: ReqlConstant
    def floor(arguments: Any) -> Any: ...
    def format(arguments: Any, kwargs: Any) -> Any: ...
    friday: ReqlConstant
    def ge(arguments: Any) -> Any: ...
    def geojson(arguments: Any) -> Any: ...
    def grant(arguments: Any, kwargs: Any) -> Any: ...
    def group(arguments: Any) -> Any: ...
    def gt(arguments: Any) -> Any: ...
    def http(url: Any, kwargs: Any) -> Any: ...
    def info(arguments: Any) -> Any: ...
    def intersects(arguments: Any) -> Any: ...
    def iso8601(arguments: Any, kwargs: Any) -> Any: ...
    january: ReqlConstant
    def json(arguments: Any) -> Any: ...
    july: ReqlConstant
    june: ReqlConstant
    def le(arguments: Any) -> Any: ...
    def line(arguments: Any) -> Any: ...
    def literal(arguments: Any) -> Any: ...
    def lt(arguments: Any) -> Any: ...
    def make_timezone(arguments: Any) -> Any: ...
    def map(arguments: Any) -> Any: ...
    march: ReqlConstant
    def max(arguments: Any) -> Any: ...
    maxval: ReqlConstant
    may: ReqlConstant
    def min(arguments: Any) -> Any: ...
    minval: ReqlConstant
    def mod(arguments: Any) -> Any: ...
    monday: ReqlConstant
    def mul(arguments: Any) -> Any: ...
    def ne(arguments: Any) -> Any: ...
    def not_(arguments: Any) -> Any: ...
    november: ReqlConstant
    def now(arguments: Any) -> Any: ...
    def object(arguments: Any) -> Any: ...
    october: ReqlConstant
    def or_(arguments: Any) -> Any: ...
    def point(arguments: Any) -> Any: ...
    def polygon(arguments: Any) -> Any: ...
    def random(arguments: Any, kwargs: Any) -> Any: ...
    def range(arguments: Any) -> Any: ...
    def reduce(arguments: Any) -> Any: ...
    def round(arguments: Any) -> Any: ...
    row: ImplicitVar
    saturday: ReqlConstant
    september: ReqlConstant
    def sub(arguments: Any) -> Any: ...
    def sum(arguments: Any) -> Any: ...
    sunday: ReqlConstant
    def table(arguments: Any, kwargs: Any) -> Any: ...
    def table_create(arguments: Any, kwargs: Any) -> Any: ...
    def table_drop(arguments: Any) -> Any: ...
    def table_list(arguments: Any) -> Any: ...
    thursday: ReqlConstant
    def time(arguments: Any) -> Any: ...
    tuesday: ReqlConstant
    def type_of(arguments: Any) -> Any: ...
    def union(arguments: Any) -> Any: ...
    def uuid(arguments: Any) -> Any: ...
    wednesday: ReqlConstant
    def js(arguments: Any, kwargs: Any) -> Any: ...
    def expr(
        self,
        val: Union[
            str,
            bytes,
            ReqlQuery,
            ReqlBinary,
            date,
            datetime,
            Mapping,
            Iterable,
            Callable,
        ],
        nesting_depth: int = ...,
    ) -> Any: ...
    ReqlQuery: Type[ReqlQuery]
    ReqlBinary: Type[ReqlBinary]
    ReqlTzinfo: Type[ReqlTzinfo]
    InvalidHandshakeStateError: Type[InvalidHandshakeStateError]
    QueryPrinter: Type[QueryPrinter]
    ReqlAuthError: Type[ReqlAuthError]
    ReqlCompileError: Type[ReqlCompileError]
    ReqlCursorEmpty: Type[ReqlCursorEmpty]
    ReqlDriverCompileError: Type[ReqlDriverCompileError]
    ReqlDriverError: Type[ReqlDriverError]
    ReqlError: Type[ReqlError]
    ReqlInternalError: Type[ReqlInternalError]
    ReqlNonExistenceError: Type[ReqlNonExistenceError]
    ReqlOpFailedError: Type[ReqlOpFailedError]
    ReqlOpIndeterminateError: Type[ReqlOpIndeterminateError]
    ReqlOperationError: Type[ReqlOperationError]
    ReqlPermissionError: Type[ReqlPermissionError]
    ReqlQueryLogicError: Type[ReqlQueryLogicError]
    ReqlResourceLimitError: Type[ReqlResourceLimitError]
    ReqlRuntimeError: Type[ReqlRuntimeError]
    ReqlServerCompileError: Type[ReqlServerCompileError]
    ReqlTimeoutError: Type[ReqlTimeoutError]
    ReqlUserError: Type[ReqlUserError]
    # Methods
    def set_loop_type(self, library: Optional[str] = None) -> None: ...

r: RethinkDB
